### ISSUE TITLE
Provide a way for CSL JSON to store extra / custom fields

### ISSUE THREAD

**Issue by dhimmel** [citation-style-language/schema#277]
In https://github.com/citation-style-language/documentation/issues/97, there's been much discussion on whether to add a way for CSL JSON to specify extra fields that are not part of the spec currently.

Currently, the CSL JSON Data Schema sets the following for items:

https://github.com/citation-style-language/schema/blob/c2b2eee63e45e964f08dc56494bea85ad2a59d51/schemas/input/csl-data.json#L426

This means that additional fields are not allowed as per the schema.

Some points in favor and against that I'm migrating here:

By @dhimmel at https://github.com/citation-style-language/documentation/issues/97#issuecomment-649782124:

> Custom variables are inevitable and required for certain use cases. We use the note cheater syntax in Manubot to store variants of id ([example](https://github.com/manubot/manubot/blob/47b03e0c202e6a0561e6548ba08a4ad790f56eee/manubot/cite/tests/test_csl_item.py#L110-L126)). Since custom variables are inevitable, I think it's best to consider the most effective and least problematic method for storing them.

By @bwiernik in https://github.com/citation-style-language/documentation/issues/97#issuecomment-650152255:

> I'll reiterate my opinion that CSL should not accommodate non-CSL variables. A major strength of CSL compared to BibTeX, in my opinion, is the way it has not embraced user-specific data entry. I believe that Sebastian has expressed similar sentiments.

From @bdarcus in https://github.com/citation-style-language/documentation/issues/97#issuecomment-650157412:

> Why do we care what people or applications put in the input data, if we don't care what they embed in the note field in some non-standard syntax?
>
> CSL JSON is being used for data exchange, and I certainly wouldn't want my custom data stripped from the output, even if it has no impact on citation processing. I might want to run a script on that output, for example, to generate some other output.

I will follow up with an additional post about possible implementations. But wanted to get this issue started to keep discussion consolidated.

**Comment by dhimmel** [comment]
Possible implementations based on a [Manubot-outputed CSL JSON example](https://github.com/greenelab/connectivity-search-manuscript/blob/70b1da8ac787ed9d8f3ee2aa763a8a16fb66b7f3/references.json#L898-L958):

```yaml
# method 1. current
- id: O21tn8vf
  type: article-journal 
  note: "standard_id: doi:10.7554/elife.26726"
# method 2. extra variables in item root (currently forbidden)
- id: O21tn8vf
  type: article-journal 
  standard_id: doi:10.7554/elife.26726
# method 3. extra variables in designated object (currently forbidden)
# many field names possible: extras, csl_extras, custom, additional, ...
- id: O21tn8vf
  type: article-journal
  extras:
    standard_id: doi:10.7554/elife.26726 
```
