### ISSUE TITLE
Multilingual data and style structures

### ISSUE THREAD

**Issue by bwiernik** [citation-style-language/schema#332]
We started to discuss multilingual data structures here: https://github.com/citation-style-language/schema/issues/327

In terms of data structures, my inclination is that storing multilingual variants should occur at the field-level. So, any field might be object with `value`, `language`, and `translated` elements. The `translated` element would be an array with elements holding `value` and `language` elements. Subordinate elements without a `language` would inherit `language` from their parent. That would have 3 benefits:
1. It would permit simple indication that a field is a different language than the item (e.g., an English article published in a German journal). 
1. It would jive with https://juris-m.readthedocs.io/en/latest/dev-sync-simplification.html
1. It would provide a consistent structure for providing translations of one or more fields for an item.

_Originally posted by @bwiernik in https://github.com/citation-style-language/schema/issues/327#issuecomment-666385146_

**Comment by denismaier** [comment]
That looks like a sound approach. 
Ideally, we would still allow a flat string approach as a simpler alternative if no multilingual data input is needed. So you could do:

```
publisher: Oxford University Press
```

Or:

```
publisher: 
  value: whatever
  language: ar
  language-alternate:
    value: Transliteration of the publisher's Arabic name
    language: ar-alc97
```
